using System;
namespace SF.Expand.SAF.CorePublicItf
{
	[Serializable]
	public enum TokenEventOperation
	{
		cTOKEN_ENABLE = 1,
		cTOKEN_DISABLE = 0,
		cTOKEN_CANCEL = 9,
		cTOKEN_UNDEFINED = 99,
		cTOKEN_READY_TO_DEPLOY = 98,
		cTOKEN_CREATED = 100,
		cTOKEN_REQUEST_CHALLENGE,
		cTOKEN_REQUEST_VALIDATION,
		cTOKEN_START_SERVER_AUTHENTICATION,
		cTOKEN_REQUEST_SYNCHRONIZATION,
		cTOKEN_RESET_ACTIVE_CHALLENGE,
		cTOKEN_RESET_MOVING_FACTOR,
		cTOKEN_HTTP_DEPLOY_REQUESTED,
		cTOKEN_EMAIL_DEPLOY_REQUESTED,
		cTOKEN_SOCKET_DEPLOY_REQUESTED,
		cTOKEN_SMS_DEPLOY_REQUESTED,
		cTOKEN_REQUEST_SMS_GATEWAY_SERVICE = 151,
		cTOKEN_REQUEST_EMAIL_GATEWAY_SERVICE,
		cTOKEN_AUTENTICATION_SUCESS = 0,
		cTOKEN_AUTENTICATION_SUCESS_BUT_SYNCHRONIZED = 200,
		cTOKEN_AUTENTICATION_FAIL = -1,
		cTOKEN_AUTENTICATION_FAIL_TOKEN_STATUS = 201,
		cTOKEN_AUTENTICATION_FAIL_INVALID_TOKENPORASSWORD,
		cTOKEN_AUTENTICATION_FAIL_INVALID_TOKENPORASSWORD_MULTIPLE = 205,
		cTOKEN_AUTENTICATION_FAIL_INVALIDDATA_PASSWORDVALIDATION = 203,
		cTOKEN_AUTENTICATION_FAIL_TOKEN_NOTFOUNDORCANCELED
	}
}
