using System;
namespace SF.Expand.SAF.CorePublicItf
{
	[Serializable]
	public enum TokenEventOperation
	{
		cTOKEN_ENABLE = 1,
		cTOKEN_DISABLE = 0,
		cTOKEN_CANCEL = 9,
		cTOKEN_UNDEFINED = 99,
		cTOKEN_READY_TO_DEPLOY = 98,
		cTOKEN_CREATED = 100,
		cTOKEN_REQUEST_CHALLANGE,
		cTOKEN_REQUEST_VALIDATION,
		cTOKEN_START_SERVER_AUTHENTICATION,
		cTOKEN_REQUEST_SYNCHRONIZATION,
		cTOKEN_RESET_ACTIVE_CHALLANGE,
		cTOKEN_RESET_MOVING_FACTOR
	}
}
